# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from clickhouse_sqlalchemy import engines
from sqlalchemy import Column, text

from tushare_integration.models.core import Base, Date, DateTime, Float, Integer, String


class CbShare(Base):
    """可转债转股结果"""

    __tablename__: str = 'cb_share'
    __api_id__: ClassVar[int] = 247
    __api_name__: ClassVar[str] = 'cb_share'
    __api_title__: ClassVar[str] = '可转债转股结果'
    __api_info_title__: ClassVar[str] = '可转债转股结果'
    __api_path__: ClassVar[List[str]] = ['数据接口', '债券', '可转债转股结果']
    __api_path_ids__: ClassVar[List[int]] = [2, 184, 247]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ['ts_code', 'publish_date']
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        'ts_code': {'type': 'str', 'required': True, 'description': '转债代码，支持多值输入'},
        'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'},
        'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'},
    }

    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '可转债转股结果',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
        },
    )

    ts_code = Column('ts_code', String(16), nullable=False, default="", server_default=text("''"), comment='债券代码')
    bond_short_name = Column(
        'bond_short_name', String(), nullable=False, default="", server_default=text("''"), comment='债券简称'
    )
    publish_date = Column(
        'publish_date',
        Date,
        nullable=False,
        default="1970-01-01",
        server_default=text("'1970-01-01'"),
        comment='公告日期',
    )
    end_date = Column(
        'end_date',
        Date,
        nullable=False,
        default="1970-01-01",
        server_default=text("'1970-01-01'"),
        comment='统计截止日期',
    )
    issue_size = Column(
        'issue_size', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='可转债发行总额'
    )
    convert_price_initial = Column(
        'convert_price_initial',
        Float,
        nullable=False,
        default=0.0,
        server_default=text("'0.0'"),
        comment='初始转换价格',
    )
    convert_price = Column(
        'convert_price', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='本次转换价格'
    )
    convert_val = Column(
        'convert_val', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='本次转股金额'
    )
    convert_vol = Column(
        'convert_vol', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='本次转股数量'
    )
    convert_ratio = Column(
        'convert_ratio', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='本次转股比例'
    )
    acc_convert_val = Column(
        'acc_convert_val', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='累计转股金额'
    )
    acc_convert_vol = Column(
        'acc_convert_vol', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='累计转股数量'
    )
    acc_convert_ratio = Column(
        'acc_convert_ratio', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='累计转股比例'
    )
    remain_size = Column(
        'remain_size', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='可转债剩余金额'
    )
    total_shares = Column(
        'total_shares', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='转股后总股本'
    )
