# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using black

from sqlalchemy import Column, text
from clickhouse_sqlalchemy import engines
from typing import ClassVar, Dict, Any, List

from tushare_integration.models.core import String, Integer, Float, Date, DateTime, Base


class CyqChips(Base):
    """每日筹码分布"""

    __tablename__: str = 'cyq_chips'
    __api_id__: ClassVar[int] = 294
    __api_name__: ClassVar[str] = 'cyq_chips'
    __api_title__: ClassVar[str] = '每日筹码分布'
    __api_info_title__: ClassVar[str] = '每日筹码分布'
    __api_path__: ClassVar[List[str]] = ['数据接口', '沪深股票', '特色数据', '每日筹码分布']
    __api_path_ids__: ClassVar[List[int]] = [2, 14, 291, 294]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ['ts_code', 'trade_date']
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {'ts_code': {'type': 'str', 'required': True, 'description': '股票代码'}, 'trade_date': {'type': 'str', 'required': False, 'description': '交易日期（YYYYMMDD）'}, 'start_date': {'type': 'str', 'required': False, 'description': '开始日期'}, 'end_date': {'type': 'str', 'required': False, 'description': '结束日期'}, 'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'}, 'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'}}
    
    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '每日筹码分布',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
        }
    )
    
    ts_code = Column('ts_code', String(16), nullable=False, default="", server_default=text("''"), comment='股票代码')
    trade_date = Column('trade_date', Date, nullable=False, default="1970-01-01", server_default=text("'1970-01-01'"), comment='交易日期')
    price = Column('price', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='成本价格')
    percent = Column('percent', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='价格占比(%)')