# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using black

from sqlalchemy import Column, text
from clickhouse_sqlalchemy import engines
from typing import ClassVar, Dict, Any, List

from tushare_integration.models.core import String, Integer, Float, Date, DateTime, Base


class FutHolding(Base):
    """每日持仓排名"""

    __tablename__: str = 'fut_holding'
    __api_id__: ClassVar[int] = 139
    __api_name__: ClassVar[str] = 'fut_holding'
    __api_title__: ClassVar[str] = '每日持仓排名'
    __api_info_title__: ClassVar[str] = '每日成交持仓排名'
    __api_path__: ClassVar[List[str]] = ['数据接口', '期货', '每日持仓排名']
    __api_path_ids__: ClassVar[List[int]] = [2, 134, 139]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = []
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {'trade_date': {'type': 'str', 'required': False, 'description': '交易日期'}, 'symbol': {'type': 'str', 'required': False, 'description': '合约或产品代码'}, 'start_date': {'type': 'str', 'required': False, 'description': '开始日期'}, 'end_date': {'type': 'str', 'required': False, 'description': '结束日期'}, 'exchange': {'type': 'str', 'required': False, 'description': '交易所代码'}, 'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'}, 'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'}}
    
    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '每日持仓排名',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
        }
    )
    
    trade_date = Column('trade_date', Date, nullable=False, default="1970-01-01", server_default=text("'1970-01-01'"), comment='交易日期')
    symbol = Column('symbol', String(), nullable=False, default="", server_default=text("''"), comment='合约代码或类型')
    broker = Column('broker', String(), nullable=False, default="", server_default=text("''"), comment='期货公司会员简称')
    vol = Column('vol', Integer, nullable=False, default=0, server_default=text("'0'"), comment='成交量')
    vol_chg = Column('vol_chg', Integer, nullable=False, default=0, server_default=text("'0'"), comment='成交量变化')
    long_hld = Column('long_hld', Integer, nullable=False, default=0, server_default=text("'0'"), comment='持买仓量')
    long_chg = Column('long_chg', Integer, nullable=False, default=0, server_default=text("'0'"), comment='持买仓量变化')
    short_hld = Column('short_hld', Integer, nullable=False, default=0, server_default=text("'0'"), comment='持卖仓量')
    short_chg = Column('short_chg', Integer, nullable=False, default=0, server_default=text("'0'"), comment='持卖仓量变化')
    exchange = Column('exchange', String(), nullable=False, default="", server_default=text("''"), comment='交易所')