# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from clickhouse_sqlalchemy import engines
from sqlalchemy import Column, text

from tushare_integration.models.core import Base, Date, DateTime, Float, Integer, String


class KplConceptCons(Base):
    """题材成分(开盘啦)"""

    __tablename__: str = 'kpl_concept_cons'
    __api_id__: ClassVar[int] = 351
    __api_name__: ClassVar[str] = 'kpl_concept_cons'
    __api_title__: ClassVar[str] = '题材成分(开盘啦)'
    __api_info_title__: ClassVar[str] = '开盘啦题材成分'
    __api_path__: ClassVar[List[str]] = ['数据接口', '沪深股票', '打板专题数据', '题材成分（开盘啦）']
    __api_path_ids__: ClassVar[List[int]] = [2, 14, 346, 351]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ['ts_code', 'cons_code', 'trade_date']
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        'ts_code': {'type': 'str', 'required': False, 'description': '题材代码'},
        'trade_date': {'type': 'str', 'required': False, 'description': '交易日期'},
        'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'},
        'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'},
    }

    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '题材成分(开盘啦)',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
        },
    )

    ts_code = Column('ts_code', String(16), nullable=False, default="", server_default=text("''"), comment='题材ID')
    name = Column('name', String(), nullable=False, default="", server_default=text("''"), comment='题材名称')
    cons_name = Column('cons_name', String(), nullable=False, default="", server_default=text("''"), comment='股票名称')
    cons_code = Column('cons_code', String(), nullable=False, default="", server_default=text("''"), comment='股票代码')
    trade_date = Column(
        'trade_date',
        Date,
        nullable=False,
        default="1970-01-01",
        server_default=text("'1970-01-01'"),
        comment='交易日期',
    )
    desc = Column('desc', String(), nullable=False, default="", server_default=text("''"), comment='描述')
    hot_num = Column('hot_num', String(), nullable=False, default="", server_default=text("''"), comment='人气值')
