# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from clickhouse_sqlalchemy import engines
from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_integration.models.core import Base, Date, DateTime, Float, Integer, String


class StkAuction(Base):
    """开盘竞价成交(当日)"""

    __tablename__: str = 'stk_auction'
    __api_id__: ClassVar[int] = 369
    __api_name__: ClassVar[str] = 'stk_auction'
    __api_title__: ClassVar[str] = '开盘竞价成交(当日)'
    __api_info_title__: ClassVar[str] = '当日集合竞价'
    __api_path__: ClassVar[List[str]] = ['数据接口', '沪深股票', '打板专题数据', '开盘竞价成交（当日）']
    __api_path_ids__: ClassVar[List[int]] = [2, 14, 346, 369]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ['ts_code', 'trade_date']
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        'ts_code': {'type': 'str', 'required': False, 'description': '股票代码'},
        'trade_date': {'type': 'str', 'required': False, 'description': '交易日期（YYYYMMDD格式，下同)'},
        'start_date': {'type': 'str', 'required': False, 'description': '开始日期'},
        'end_date': {'type': 'str', 'required': False, 'description': '结束日期'},
        'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'},
        'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'},
    }

    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '开盘竞价成交(当日)',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
            # Databend引擎
            'databend_cluster_by': __primary_key__,
        },
    )

    ts_code = Column('ts_code', String(16), nullable=False, default="", server_default=text("''"), comment='股票代码')
    trade_date = Column(
        'trade_date',
        Date,
        nullable=False,
        default="1970-01-01",
        server_default=text("'1970-01-01'"),
        comment='交易日期',
    )
    vol = Column('vol', Integer, nullable=False, default=0, server_default=text("'0'"), comment='成交量')
    price = Column('price', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='成交均价(元)')
    amount = Column('amount', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='成交金额(元)')
    pre_close = Column('pre_close', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='昨收价')
    turnover_rate = Column(
        'turnover_rate', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='换手率(%)'
    )
    volume_ratio = Column(
        'volume_ratio', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='量比'
    )
    float_share = Column(
        'float_share', Float, nullable=False, default=0.0, server_default=text("'0.0'"), comment='流通股本(万股)'
    )
