# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using black

from sqlalchemy import Column, text
from clickhouse_sqlalchemy import engines
from typing import ClassVar, Dict, Any, List

from tushare_integration.models.core import String, Integer, Float, Date, DateTime, Base


class ThsIndex(Base):
    """同花顺概念和行业列表"""

    __tablename__: str = 'ths_index'
    __api_id__: ClassVar[int] = 259
    __api_name__: ClassVar[str] = 'ths_index'
    __api_title__: ClassVar[str] = '同花顺概念和行业列表'
    __api_info_title__: ClassVar[str] = '同花顺板块指数'
    __api_path__: ClassVar[List[str]] = ['数据接口', '指数', '同花顺概念和行业列表']
    __api_path_ids__: ClassVar[List[int]] = [2, 93, 259]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = []
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {'ts_code': {'type': 'str', 'required': False, 'description': '指数代码'}, 'exchange': {'type': 'str', 'required': False, 'description': '市场类型A-a股票 HK-港股 US-美股'}, 'type': {'type': 'str', 'required': False, 'description': '指数类型 N-板块指数 S-同花顺特色指数'}, 'limit': {'type': 'int', 'required': False, 'description': '单次返回数据长度'}, 'offset': {'type': 'int', 'required': False, 'description': '请求数据的开始位移量'}}
    
    __mapper_args__ = {'primary_key': __primary_key__}
    __table_args__ = (
        # ClickHouse引擎
        engines.ReplacingMergeTree(order_by=__primary_key__),
        {
            'comment': '同花顺概念和行业列表',
            # MySQL引擎
            'mysql_engine': 'InnoDB',
            # StarRocks引擎
            'starrocks_primary_key': ','.join(__primary_key__),
            'starrocks_order_by': ','.join(__primary_key__),
            # Apache Doris引擎
            'doris_unique_key': __primary_key__,
        }
    )
    
    ts_code = Column('ts_code', String(16), nullable=False, default="", server_default=text("''"), comment='代码')
    name = Column('name', String(), nullable=False, default="", server_default=text("''"), comment='名称')
    count = Column('count', Integer, nullable=False, default=0, server_default=text("'0'"), comment='成分个数')
    exchange = Column('exchange', String(), nullable=False, default="", server_default=text("''"), comment='交易所')
    list_date = Column('list_date', Date, nullable=False, default="1970-01-01", server_default=text("'1970-01-01'"), comment='上市日期')
    type = Column('type', String(), nullable=False, default="", server_default=text("''"), comment='N概念指数S特色指数')